# Generated by Django 5.0.7 on 2024-07-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('website_traffic', models.JSONField()),
                ('top_performing_pages', models.JSONField()),
            ],
        ),
    ]
